version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        - VITE_HOST=${VITE_HOST}
        - VITE_TG_BOT_NAME=${VITE_TG_BOT_NAME}
        - VITE_DATA_AUTH_URL=${VITE_DATA_AUTH_URL}
        - VITE_DOMEN=${VITE_DOMEN}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_IMAGE_URL=${VITE_API_IMAGE_URL}
    ports:
      - '5174:5174'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
